### PR TITLE
fix infinite property is boolean #39

### LINKED ISSUE #39: Infinite property should be boolean
`Map` has a property `Infinite`, currently this is of `int` type, but should be `bool`

### PR DESCRIPTION
**Pull request by u5surf**
**Checklist**
Ensure all of these are completed before opening the PR:
 - [o] Run `goimports`
 - [o] Read the [contribution guide](https://github.com/bcvery1/tilepix/blob/master/CONTRIBUTING.md)
 - [o] Read the [code of conduct](https://github.com/bcvery1/tilepix/blob/master/CODE_OF_CONDUCT.md)
 - [o] Read the [coding standards](https://github.com/bcvery1/tilepix/blob/master/CODING_STANDARDS.md)
 - [o] Tests run with `-race`
 - [o] Tests written to cover any new code
 - [o] Added yourself to the [contributors file](https://github.com/bcvery1/tilepix/blob/master/CONTRIBUTORS.md)

**Describe the changes**
#39 

**Closing issues**
Resolves #39

### CODE REVIEW

File: tmx.go [hunk 1]
```diff
@@ -65,8 +65,8 @@ func Read(r io.Reader) (*Map, error) {
 		return nil, err
 	}
 
-	if m.Infinite == 1 {
-		log.WithError(ErrInfiniteMap).Error("Read: map has attribute 'infinite=1', not supported")
+	if m.Infinite == true {
```
Comment (bcvery1) [inline tmx.go]: No need to check this explicitly, should use `if m.Infinite {` instead

File: testdata/base64-gzip.tmx [hunk 2]
```diff
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<map version="1.2" tiledversion="1.2.2" orientation="orthogonal" renderorder="right-down" width="32" height="32" tilewidth="8" tileheight="8" infinite="0" nextlayerid="3" nextobjectid="2">
+<map version="1.2" tiledversion="1.2.2" orientation="orthogonal" renderorder="right-down" width="32" height="32" tilewidth="8" tileheight="8" infinite="false" nextlayerid="3" nextobjectid="2">
```
Comment (bcvery1) [inline testdata/base64-gzip.tmx]: The property in the TMX files is written as an `int` by Tiled, so we should leave them as 0's or 1's, could you revert the changes on the TMX files please
